apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
      - name: hello-world-app
        # Fixed to match your specific project and region
        image: us-west1-docker.pkg.dev/gke-flask-2026-01-27/gke-flask-repo/gke-flask-img:v1
        ports:
        - containerPort: 8080
