apiVersion: v1
kind: Service
metadata:
  name: grocery-service
  namespace: grocery-app
spec:
  type: LoadBalancer
  ports:
  - port: 80         
    targetPort: 5000 
  selector:
    app: grocery-app
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: grocery-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis