# ---------------------------------------------------------------
# secrets.yaml
# ---------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: sentiment-secrets
type: Opaque
data:
---
